### PR TITLE
Recognize .cxx files as C/C++

### PR DESCRIPTION
**Pull request by uk-ar**
Some organizations use .cxx files as c++ source files.

### CODE REVIEW

**Comment by uk-ar** [comment]
Hello!

I am really happy if you can merge this pull request.
What should I do for the next step? @lguychard @felixfbecker

**Comment by lguychard** [comment]
Hi @uk-ar,

Could you run prettier (`yarn prettier`) so that your branch passes CI? https://buildkite.com/sourcegraph/sourcegraph-basic-code-intel/builds/1237#df76d36b-056e-48a0-a71b-35b3feb51e4d

Thanks!

**Comment by uk-ar** [comment]
Hi @lguychard ,

Thank you for your reply! 

I cannot see buildkite result(Page not found). But I run prettier and commit.
https://buildkite.com/sourcegraph/sourcegraph-basic-code-intel/builds/1237#df76d36b-056e-48a0-a71b-35b3feb51e4d

Could you review my new commit?

Thanks!

**Comment by chrismwendt** [comment]
This will work once https://github.com/sourcegraph/sourcegraph/pull/5747 is merged in.

**Pull request merged**
